Implement account registration in the wizard
nextcloud/gsoc_client pull request #10
Opened 2017-07-11 20:15 UTC by juliushaertl

Based on #9 

![2017-07-11-221227_750x507_scrot](https://user-images.githubusercontent.com/3404133/28088501-23f08e28-6686-11e7-914c-61f7a9afd74a.png)

![2017-07-11-221235_750x507_scrot](https://user-images.githubusercontent.com/3404133/28088505-26034f2a-6686-11e7-8d9f-78c931fc3bc4.png)

ToDo:
- [ ] Implement pending account type for registrations
- [ ] Frequently check for registration status
- [ ] Setup HttpCredentials with app password after registration is complete

2017-07-22 08:32 UTC, rullzer requested changes
I'll have a more detailed look soon

2017-07-22 08:32 UTC, rullzer commented on src/gui/ocsregistrationjob.h
> +     * This is needed so we can update the share objects properly
Copy paste :wink:

2017-07-22 08:32 UTC, rullzer commented on src/gui/wizard/owncloudproviderlistpage.h
> +    void setCountry(QString current);
use http://doc.qt.io/qt-5/qlocale.html#Country-enum ?

2017-08-28 08:09 UTC, juliushaertl commented
Closing in favour of https://github.com/nextcloud/gsoc_client/pull/17

2017-08-28 08:09 UTC, closed without merging